@extends('layouts.master')
@section('title', 'Welcome!')
@section('content')
<div>
    @include ('layouts.bb-nav')
</div>
<div class="container">
    <h2>Bordered Table</h2>
    <table class="table table-bordered">
        <thead>
            <th rowspan="12">School Name: BAIS</th>
        </thead>
        <thead>
        <tr>
            <th>Number</th>
            <th>FG</th>
            <th>3's</th>
            <th>FT</th>
            <th>RB</th>
            <th>TO</th>
            <th>Assists</th>
            <th>Steals</th>
            <th>Blocks</th>
            <th>Fouls</th>
        </tr>
        </thead>
    <tbody>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
    </tbody>
    </table>
</div>
<div class="container">
    <h2>Team 2</h2>
    <table class="table table-bordered">
        <thead>
            <th rowspan="12">School Name: SIS</th>
        </thead>
        <thead>
        <tr>
            <th>Number</th>
            <th>FG</th>
            <th>3's</th>
            <th>FT</th>
            <th>RB</th>
            <th>TO</th>
            <th>Assists</th>
            <th>Steals</th>
            <th>Blocks</th>
            <th>Fouls</th>
        </tr>
        </thead>
    <tbody>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
        <tr>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td>
            <td>John</td> 
        </tr>
    </tbody>
    </table>
</div>
@endsection
